# Generated by Django 5.0.3 on 2024-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBuddie_s_Mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.TextField(max_length=128),
        ),
    ]
