# Generated by Django 5.0.3 on 2024-03-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBuddie_s_Mart', '0002_alter_myuser_number_alter_myuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
