# Generated by Django 5.0.3 on 2024-03-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBuddie_s_Mart', '0010_remove_product_map_location_remove_product_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
