# Generated by Django 5.0.3 on 2024-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBuddie_s_Mart', '0011_rename_image_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='top_selling',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
