# Generated by Django 5.0.3 on 2024-03-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBuddie_s_Mart', '0015_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
